mlid:
  'menu_link_content:ad8a7e1a-7a6f-4115-af99-d6a030f16443':
    roles: {  }
    access_check: false
  'menu_link_content:f94cd2da-f4e9-42ed-b3d0-0a96e77a8cc5':
    roles:
      - anonymous
    access_check: false
  'menu_link_content:73657f48-5a08-46dc-a442-41eab7da566e':
    roles: {  }
    access_check: false
  'menu_link_content:8cee9ab9-0e8b-463e-bee6-db60a7fcd62b':
    roles:
      - authenticated
    access_check: false
  'menu_link_content:5342535a-dc78-4075-9b0d-902e486d8229':
    roles:
      - authenticated
    access_check: false
  'menu_link_content:4ac1107b-0249-400d-96a3-76de9010e659':
    roles:
      - anonymous
    access_check: false
  'menu_link_content:7f002a23-a244-428e-8392-e419653de383':
    roles:
      - anonymous
    access_check: false
  'menu_link_content:3e73f6d8-7f72-4de0-a4e6-cf08295d75e4':
    roles: {  }
    access_check: false
  'menu_link_content:c9c228a6-84a7-45ab-8468-3e9c6dce9a3f':
    roles: {  }
    access_check: false
  'menu_link_content:0823f899-06a1-42b3-aff6-59acb9c7ef73':
    roles: {  }
    access_check: false
  'menu_link_content:14686f99-14e9-4151-85d0-7b34393a111a':
    roles: {  }
    access_check: false
  'menu_link_content:2cf4a9f1-be3d-4c80-8c36-4686e5919058':
    roles: {  }
    access_check: false
  'menu_link_content:f574cfa7-7c0b-4dbc-8456-d18265e4f52b':
    roles: {  }
    access_check: false
  'menu_link_content:49f22a4c-0f02-4523-a4c3-fa488ff71386':
    roles: {  }
    access_check: false
